#!/usr/bin/env ruby
# frozen_string_literal: true

# The commands live in KubernetesHelper::CLI so that they can be unit tested; see
# the note there on why a case statement in this file could not be measured.
require 'kubernetes_helper'

KubernetesHelper::CLI.call(ARGV)
